name: Auto Bug Fix Agent
on:
  issues:
    types: [opened, labeled]
jobs:
  run-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone Agent Repo
        run: git clone https://github.com/rashisachan/Devops-Agent.git agent-src

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r agent-src/requirements.txt

      - name: Check label
        run: echo "Label is ${{ github.event.label.name }}"

      - name: Run agent
        if: |
          github.event.label.name == 'auto-fix' ||
          contains(toJSON(github.event.issue.labels), 'auto-fix')
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        run: python agent-src/main.py ${{ github.event.issue.number }}
